version: '2'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: node-container
    ports:
      - "3000:3000"
      - "8000:8000"
    volumes:
      - ./:/code